#!/bin/bash

# Open with xdg
if [ $( which xdg-open ) ]; then
	alias open=xdg-open
fi

# pretty log
alias lg="git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"

# make a git repo within a girectory 
alias creategit="git init && git add -A && git commit -m \"Initial commit\""

# some more ls aliases
alias ll='ls -alFh'
alias la='ls -Ah'
alias l='ls -CFh'

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# Make an image from text
function makeimage()
{
	FILE=$( mktemp "image_XXXXXX.jpg" )
	echo "Making $FILE"
	convert -fill white -pointsize 50 -background black label:"$*"  -flatten $FILE
}

# Watch youtube as ascii!
function youtubeascii()
{
	youtube-dl http://www.youtube.com/watch?v=$1 -o - | mplayer -vo aa -monitorpixelaspect 0.5 - 
}
