" =======================================================================
" basic custom rolled ~./vimrc

" color and highlighting
syntax enable
colorscheme pablo

" always show the status line
set laststatus=2
set statusline=\ %F%m%r%h\ %w\ \ CWD:\ %r%{getcwd()}%h\ \ \ Line:\ %l

" set tab length to 4
set tabstop=4

" set visual autocomplete
set wildmenu

" Make search more interactive and visual
set incsearch
set hlsearch

" use 0 for first non whitespace (otherwise it's kinda annoying in code
map 0 ^

" set relative line numbers for commands
set number
set relativenumber

" set encoding
set encoding=utf-8

" set to use a dot for whitespace and other helpers
set list
set listchars=tab:▸\ ,trail:·,extends:>,precedes:<

" Map buttons to remove and add line numbers, useful for quick copy/paste
map <F2> :set nonumber norelativenumber<CR>
map <F3> :set number relativenumber<CR>

" Map to show and remove whitespace
map <F5> :set nolist<CR>
map <F6> :set list<CR>

" use the system clipboard
set clipboard=unnamedplus
