" =======================================================================
" Vundle stuff
set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" The following are examples of different formats supported.
" Keep Plugin commands between vundle#begin/end.
" plugin on GitHub repo
"Plugin 'tpope/vim-fugitive'
" plugin from http://vim-scripts.org/vim/scripts.html
"Plugin 'L9'
" Git plugin not hosted on GitHub
"Plugin 'git://git.wincent.com/command-t.git'
" git repos on your local machine (i.e. when working on your own plugin)
"Plugin 'file:///home/gmarik/path/to/plugin'
" The sparkup vim script is in a subdirectory of this repo called vim.
" Pass the path to set the runtimepath properly.
"Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}
" Install L9 and avoid a Naming conflict if you've already installed a
" different version somewhere else.
"Plugin 'ascenator/L9', {'name': 'newL9'}

" YouCompleteMe
Plugin 'Valloric/YouCompleteMe'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line

" =======================================================================
" basic custom rolled ~./vimrc

" color and highlighting
syntax enable
colorscheme pablo

" always show the status line
set laststatus=2
set statusline=\ %F%m%r%h\ %w\ \ CWD:\ %r%{getcwd()}%h\ \ \ Line:\ %l

" set tab length to 4
set tabstop=4

" set visual autocomplete
set wildmenu

" Make search more interactive and visual
set incsearch
set hlsearch

" use 0 for first non whitespace (otherwise it's kinda annoying in code
map 0 ^

" set relative line numbers for commands
set number
set relativenumber

" set encoding
set encoding=utf-8

" set to use a dot for whitespace and other helpers
set list
set listchars=tab:▸\ ,trail:·,extends:>,precedes:<

" Map buttons to remove and add line numbers, useful for quick copy/paste
map <F2> :set nonumber norelativenumber<CR>
map <F3> :set number relativenumber<CR>

" Map to show and remove whitespace
map <F5> :set nolist<CR>
map <F6> :set list<CR>

" use the system clipboard
set clipboard=unnamedplus
